---
unseal_keys_dir_output: "{{ playbook_dir }}/unsealKey"
root_token_dir_output: "{{ playbook_dir }}/rootKey"
ro_token_dir_output: "{{ playbook_dir }}/roKey"
rw_token_dir_output: "{{ playbook_dir }}/rwKey"